In [1]:
import sys
import os

import dataclasses

In [2]:
def add_alphafold_to_path():
    # Modify the module path (if required) so that we can import
    # modules from this repository
    module_path = os.path.expanduser("~/software/alphafold")
    if module_path not in sys.path:
        sys.path.append(module_path)

add_alphafold_to_path()

### Data input

In [3]:
from alphafold.common.protein import from_pdb_string

In [23]:
with open("./dist_scores/SadA_NSLeu_Corrected_3701_0002.pdb", "r") as fh:
    prot = from_pdb_string(fh.read())
    
dataclasses.fields(prot)

(Field(name='atom_positions',type=<class 'numpy.ndarray'>,default=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),
 Field(name='aatype',type=<class 'numpy.ndarray'>,default=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),
 Field(name='atom_mask',type=<class 'numpy.ndarray'>,default=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,init=True,repr=True,hash=None,compare=True,metadata=mappingproxy({}),_field_type=_FIELD),
 Field(name='residue_index',type=<class 'numpy.ndarray'>,default=<dataclasses._MISSING_TYPE object at 0x7f15597d3dc0>,default_factory=<dataclasses._MISSING_TYPE object at 0x7f1559

In [30]:
NUM_RES = len(prot.aatype)

In [17]:
print(prot.atom_mask.shape)
prot.atom_mask

(273, 37)


array([[1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       ...,
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 0.],
       [1., 1., 1., ..., 0., 0., 1.]])

In [18]:
print(prot.atom_positions.shape)
prot.atom_positions

(273, 37, 3)


array([[[-41.47900009,  16.1970005 , -21.96999931],
        [-41.0929985 ,  16.22900009, -20.5189991 ],
        [-40.41699982,  14.9289999 , -20.16699982],
        ...,
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ]],

       [[-39.46900177,  15.02799988, -19.24799919],
        [-38.74200058,  13.90600014, -18.68099976],
        [-39.44100189,  13.45600033, -17.43799973],
        ...,
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ]],

       [[-39.43899918,  12.16399956, -17.17900085],
        [-39.98099899,  11.68299961, -15.92300034],
        [-39.05599976,  11.87800026, -14.76200008],
        ...,
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ],
        [  0.        ,   0.        ,   0.        ]],

       ...,

      

In [8]:
prot.b_factors

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [19]:
prot.chain_index

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0])

In [20]:
prot.residue_index

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103, 104,
       105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117,
       118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130,
       131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143,
       144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
       157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169,
       170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 18

## Model

In [22]:
import alphafold.model.config as aconfig

In [33]:
aconfig.NUM_RES = NUM_RES

In [37]:
aconfig.model_config("model_1")

data:
  common:
    masked_msa:
      profile_prob: 0.1
      same_prob: 0.1
      uniform_prob: 0.1
    max_extra_msa: 5120
    msa_cluster_features: true
    num_recycle: 3
    reduce_msa_clusters_by_max_templates: true
    resample_msa_in_recycling: true
    template_features:
    - template_all_atom_positions
    - template_sum_probs
    - template_aatype
    - template_all_atom_masks
    - template_domain_names
    unsupervised_features:
    - aatype
    - residue_index
    - sequence
    - msa
    - domain_name
    - num_alignments
    - seq_length
    - between_segment_residues
    - deletion_matrix
    use_templates: true
  eval:
    feat:
      aatype:
      - num residues placeholder
      all_atom_mask:
      - num residues placeholder
      - null
      all_atom_positions:
      - num residues placeholder
      - null
      - null
      alt_chi_angles:
      - num residues placeholder
      - null
      atom14_alt_gt_exists:
      - num residues placeholder
      - null
   

In [34]:
import copy

In [35]:
copy.deepcopy(aconfig.CONFIG)

data:
  common:
    masked_msa:
      profile_prob: 0.1
      same_prob: 0.1
      uniform_prob: 0.1
    max_extra_msa: 1024
    msa_cluster_features: true
    num_recycle: 3
    reduce_msa_clusters_by_max_templates: false
    resample_msa_in_recycling: true
    template_features:
    - template_all_atom_positions
    - template_sum_probs
    - template_aatype
    - template_all_atom_masks
    - template_domain_names
    unsupervised_features:
    - aatype
    - residue_index
    - sequence
    - msa
    - domain_name
    - num_alignments
    - seq_length
    - between_segment_residues
    - deletion_matrix
    use_templates: false
  eval:
    feat:
      aatype:
      - num residues placeholder
      all_atom_mask:
      - num residues placeholder
      - null
      all_atom_positions:
      - num residues placeholder
      - null
      - null
      alt_chi_angles:
      - num residues placeholder
      - null
      atom14_alt_gt_exists:
      - num residues placeholder
      - null
 

In [11]:
from alphafold.model.common_modules import Linear

import numpy as np
import jax
import jax.numpy as jnp
import haiku as hk

In [12]:
def _f(x):
    m = Linear(num_output=2, num_input_dims=1, name="linear22")
    return m(x)
f = hk.transform(_f)
f

Transformed(init=<function without_state.<locals>.init_fn at 0x7f142270eb80>, apply=<function without_state.<locals>.apply_fn at 0x7f142270ec10>)

In [13]:
test_inp = prot.atom_positions.astype(jnp.float32)

In [14]:
rng_key = jax.random.PRNGKey(42)
params = f.init(x=test_inp, rng=rng_key)
params

FlatMapping({
  'linear22': FlatMapping({
                'weights': DeviceArray([[-0.34503725,  0.582498  ],
                                        [ 0.0910517 , -0.35958534],
                                        [ 0.68855035,  0.66172487]], dtype=float32),
                'bias': DeviceArray([0., 0.], dtype=float32),
              }),
})

In [15]:
prot.atom_positions.shape

(273, 37, 3)

In [16]:
output1 = f.apply(params, rng=rng_key, x=test_inp)
output1

DeviceArray([[[  0.65911406, -44.523735  ],
              [  1.5279288 , -43.35023   ],
              [  1.418686  , -42.256077  ],
              ...,
              [  0.        ,   0.        ],
              [  0.        ,   0.        ],
              [  0.        ,   0.        ]],

             [[  1.7333843 , -41.131344  ],
              [  1.7707894 , -39.929214  ],
              [  2.8268661 , -39.352043  ],
              ...,
              [  0.        ,   0.        ],
              [  0.        ,   0.        ],
              [  0.        ,   0.        ]],

             [[  2.88687   , -38.714905  ],
              [  3.8949037 , -38.02653   ],
              [  4.3929067 , -36.789577  ],
              ...,
              [  0.        ,   0.        ],
              [  0.        ,   0.        ],
              [  0.        ,   0.        ]],

             ...,

             [[ -9.251547  , -33.932358  ],
              [ -9.040952  , -33.156532  ],
              [ -9.911647  , -32.60077